export const SERIALIZABLE = 'ISOLATION LEVEL SERIALIZABLE';
export const READONLY = 'ISOLATION LEVEL REPEATABLE READ READ ONLY';

export type SERIALIZABLE = typeof SERIALIZABLE;
export type READONLY = typeof READONLY;
